---
include:
  - board: nice_nano_v2
    shield: eyelash_sofle_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano_v2
    shield: eyelash_sofle_right nice_view_custom
    # 💡 解決策：右手側のビルドの瞬間だけ、競合する電源ドライバーを明示的にOFFにします
    cmake-args: -DCONFIG_ZMK_EXT_POWER=n -DCONFIG_EXT_POWER=n
  - board: nice_nano_v2
    shield: settings_reset
